### ISSUE TITLE
We need guidance for Codespaces

### ISSUE THREAD

**Issue by robotdad** [microsoft/semanticworkbench#15]
The [devcontainer readme](https://github.com/microsoft/semanticworkbench/tree/main/.devcontainer) has important information in it about how to run the workbench in the Codespaces environment. We should provide some central guidance about using Codespaces and make sure it is referenced throughout setup instructions.

This should also cover using local devcontainers.

**Comment by bkrabach** [comment]
@robotdad - I updated that readme with more info regarding Codespaces in general, would you like to add any additional contents for local devcontainers to it?

**Comment by robotdad** [comment]
That's great! Thanks. I can take a future pass on something for local devcontainers.
