### ISSUE TITLE
Can't connect to example .Net assistant services (they are there but fail on saving)

### ISSUE THREAD

**Issue by RupertWalsh** [microsoft/semanticworkbench#17]
I got this mostly running on my Windows 11 ARM machine! Deployed the service and app in a WSL2 dev container from VSCode and everything works fine with the canonical agent. The app and service didn't start automatically though, I needed to start them both myself as per the instructions. App was fine but for starting the service I needed to use the -h parameter to specify 127.0.0.1 as the host (and -p 3000 for the port) when starting the service.

Then I tried running the sample .NET agents from Visual Studio on the Windows host machine. I could run them both and they were available in the App as Assistant Services to select when creating a new Assistant Instance, but after naming them and trying to Save they would fail with the following error:
 
Service error: Failed to connect to assistant at url http://127.0.0.1:9001/myagents/0e1bcd40-d26a-4bb2-8bc5-c1a759b410c6; ConnectError: All connection attempts failed

**Comment by dluc** [comment]
hi @RupertWalsh. The problems you're facing might be related to the way the projects are executed, e.g. bringing WSL and containers in the picture. 

I work with the .NET examples using a simple `dotnet run`, in the same shell where SW backend and frontend processes are running - could you try this approach?

**Comment by dluc** [comment]
Another issue I found last week on WSL is with the filesystem being case sensitive and the risk of not finding config files. I've updated the examples to search for both `appsettings.Development.json` and `appsettings.development.json`
